/** @type {import('prettier').Config} */
module.exports = {
  plugins: [
    '@trivago/prettier-plugin-sort-imports',
    'prettier-plugin-css-order',
    'prettier-plugin-tailwindcss',
  ],
  pluginSearchDirs: [],
  trailingComma: 'es5',
  importOrder: [
    '^(remix)$',
    '<THIRD_PARTY_MODULES>',
    '^@fond-of/(.*)$',
    '^@images/(.*)$',
    '^@/api/(.*)$',
    '^@/hooks/(.*)$',
    '^@/components/(.*)$',
    '^@/pages/(.*)$',
    '^@/(.*)$',
  ],
  order: 'concentric-css',
  printWidth: 80,
  useTabs: false,
  tabWidth: 2,
  semi: false,
  singleQuote: true,
  quoteProps: 'as-needed',
  jsxSingleQuote: false,
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'always',
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  singleAttributePerLine: true,
}
